export const movies = [
  {
    title: "Spider-Man: Sin Camino a Casa",
    poster: "../images/1. Spider-Man No Way Home.jpg",
    summary: "Spider-Man enfrenta las consecuencias de su identidad revelada.",
    description: `Después de que Mysterio revelara su identidad al mundo, Peter Parker busca la ayuda del Doctor Strange para recuperar su vida normal. Sin embargo, un hechizo fallido abre las puertas al multiverso, trayendo amenazas de otros universos y obligando a Spider-Man a enfrentar desafíos como nunca antes.`,
    cast: [
      "Tom Holland - Petter parker / Spider-Man",
      "Zendaya - MJ",
      "Benedict Cumberbatch - Doctor Strange",
      "Willem Dafoe - Norman Osborn / Duende Verde",
      "Alfred Molina - Otto Octavius / Doctor Octopus",
    ],
    duration: "148 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "17 de diciembre de 2021",
  },
  {
    title: "Batman: El Caballero de la Noche",
    poster: "../images/2. The Dark Knight.jpg",
    summary: "Batman enfrenta al Joker en una lucha por el alma de Gotham.",
    description: `Bruce Wayne, como Batman, enfrenta a su mayor desafío cuando el Joker amenaza con sumir a Gotham en el caos. Con la ayuda de su aliado el comisionado Gordon y el fiscal Harvey Dent, deberá tomar decisiones que afectarán el destino de la ciudad.`,
    cast: [
      "Christian Bale - Bruce Wayne / Batman",
      "Heath Ledger - Joker",
      "Aaron Eckhart - Harvey Dent / Dos Caras",
      "Michael Caine - Alfred Pennyworth",
      "Gary Oldman - James Gordon",
    ],
    duration: "152 minutos",
    genre: ["Acción", "Drama", "Crimen"],
    releaseDate: "18 de julio de 2008",
  },
  {
    title: "Iron Man",
    poster: "../images/3. Iron Man.jpg",
    summary:
      "Tony Stark se convierte en Iron Man tras escapar de sus captores.",
    description: `El multimillonario genio Tony Stark es secuestrado por terroristas y obligado a construir un arma. En su lugar, diseña una armadura avanzada para escapar y, al regresar, decide usar su tecnología para luchar contra el mal como Iron Man.`,
    cast: [
      "Robert Downey Jr. - Tony Stark / Iron Man",
      "Gwyneth Paltrow - Pepper Potts",
      "Jeff Bridges - Obadiah Stane / Iron Monger",
      "Terrence Howard - James Rhodes",
    ],
    duration: "126 minutos",
    genre: ["Acción", "Ciencia ficción", "Aventura"],
    releaseDate: "2 de mayo de 2008",
  },
  {
    title: "Mujer Maravilla",
    poster: "../images/4. Wonder Woman.jpg",
    summary:
      "Diana Prince descubre su destino como Wonder Woman durante la Primera Guerra Mundial.",
    description: `Criada en una isla de amazonas, Diana deja su hogar para salvar al mundo cuando un piloto estadounidense llega a su tierra y le cuenta sobre la guerra mundial. En su viaje, descubre sus poderes y su verdadero destino.`,
    cast: [
      "Gal Gadot - Diana Prince / Wonder Woman",
      "Chris Pine - Steve Trevor",
      "Robin Wright - Antiope",
      "Connie Nielsen - Reina Hippolyta",
    ],
    duration: "141 minutos",
    genre: ["Acción", "Aventura", "Fantasía"],
    releaseDate: "2 de junio de 2017",
  },
  {
    title: "Pantera Negra",
    poster: "../images/5. Black Panther.jpg",
    summary:
      "T'Challa asume el trono de Wakanda mientras enfrenta desafíos internos y externos.",
    description: `Tras la muerte de su padre, T'Challa regresa a Wakanda para ser coronado rey. Sin embargo, un enemigo inesperado pone en peligro su reino y lo obliga a luchar por su pueblo y su legado como Black Panther.`,
    cast: [
      "Chadwick Boseman - T'Challa / Black Panther",
      "Michael B. Jordan - Erik Killmonger",
      "Lupita Nyong'o - Nakia",
      "Danai Gurira - Okoye",
      "Martin Freeman - Everett K. Ross",
    ],
    duration: "134 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "16 de febrero de 2018",
  },
  {
    title: "Avengers: Endgame",
    poster: "../images/6. Avengers Endgame.jpg",
    summary:
      "Los Vengadores luchan para revertir los efectos del chasquido de Thanos.",
    description: `Después de los eventos devastadores de Avengers: Infinity War, los Vengadores restantes deben unirse para deshacer el daño causado por Thanos y restaurar el orden en el universo.`,
    cast: [
      "Robert Downey Jr. - Tony Stark / Iron Man",
      "Chris Evans - Steve Rogers / Capitán América",
      "Scarlett Johansson - Natasha Romanoff / Black Widow",
      "Mark Ruffalo - Bruce Banner / Hulk",
      "Chris Hemsworth - Thor",
    ],
    duration: "181 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "26 de abril de 2019",
  },
  {
    title: "Thor: Ragnarok",
    poster: "../images/7. Thor Ragnarok.jpg",
    summary:
      "Thor debe evitar el Ragnarok enfrentando a Hela y salvando Asgard.",
    description: `Prisionero en un planeta lejano, Thor debe luchar en una arena de gladiadores contra su viejo amigo Hulk mientras busca una manera de regresar a Asgard y detener a la diosa de la muerte, Hela, quien amenaza con desatar el Ragnarok.`,
    cast: [
      "Chris Hemsworth - Thor",
      "Tom Hiddleston - Loki",
      "Cate Blanchett - Hela",
      "Mark Ruffalo - Bruce Banner / Hulk",
      "Tessa Thompson - Valkyrie",
    ],
    duration: "130 minutos",
    genre: ["Acción", "Aventura", "Comedia"],
    releaseDate: "3 de noviembre de 2017",
  },
  {
    title: "Deadpool",
    poster: "../images/8. Deadpool.jpg",
    summary: "Un antihéroe busca vengarse de quienes lo transformaron.",
    description: `Wade Wilson, un exoperativo de las fuerzas especiales convertido en mercenario, se somete a un experimento que le da habilidades de curación acelerada pero lo desfigura. Adoptando la identidad de Deadpool, busca vengarse de quienes arruinaron su vida.`,
    cast: [
      "Ryan Reynolds - Wade Wilson / Deadpool",
      "Morena Baccarin - Vanessa",
      "Ed Skrein - Ajax",
      "T.J. Miller - Weasel",
      "Brianna Hildebrand - Negasonic Teenage Warhead",
    ],
    duration: "108 minutos",
    genre: ["Acción", "Comedia", "Ciencia ficción"],
    releaseDate: "12 de febrero de 2016",
  },
  {
    title: "Guardianes de la Galaxia",
    poster: "../images/9. Guardians of the Galaxy.jpg",
    summary: "Un grupo de inadaptados se une para proteger la galaxia.",
    description: `Después de robar un misterioso orbe, Peter Quill forma una alianza con un grupo de delincuentes para evitar que caiga en las manos equivocadas y destruya el universo.`,
    cast: [
      "Chris Pratt - Peter Quill / Star-Lord",
      "Zoe Saldana - Gamora",
      "Dave Bautista - Drax el Destructor",
      "Bradley Cooper - Rocket (voz)",
      "Vin Diesel - Groot (voz)",
    ],
    duration: "121 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "1 de agosto de 2014",
  },
  {
    title: "X-Men: Dias del Futuro Pasado",
    poster: "../images/10. X-Men Days of Future Past.jpg",
    summary: "Los X-Men luchan para cambiar el pasado y salvar el futuro.",
    description: `En un futuro desolado, los X-Men envían a Wolverine al pasado para cambiar los eventos que llevaron a la creación de los Centinelas, máquinas asesinas diseñadas para exterminar mutantes.`,
    cast: [
      "Hugh Jackman - Logan / Wolverine",
      "James McAvoy - Charles Xavier (joven)",
      "Michael Fassbender - Erik Lehnsherr / Magneto (joven)",
      "Jennifer Lawrence - Raven / Mystique",
      "Patrick Stewart - Charles Xavier (mayor)",
    ],
    duration: "132 minutos",
    genre: ["Acción", "Ciencia ficción", "Aventura"],
    releaseDate: "23 de mayo de 2014",
  },
  {
    title: "Logan",
    poster: "../images/11. Logan.jpg",
    summary: "El envejecido Logan intenta proteger a una joven mutante.",
    description: `En un futuro cercano, un Logan cansado cuida al enfermo Profesor X en un escondite remoto. Su plan de retiro se ve interrumpido cuando una joven mutante perseguida por fuerzas oscuras llega en busca de ayuda.`,
    cast: [
      "Hugh Jackman - Logan / Wolverine",
      "Patrick Stewart - Charles Xavier",
      "Dafne Keen - Laura / X-23",
      "Boyd Holbrook - Donald Pierce",
      "Stephen Merchant - Caliban",
    ],
    duration: "137 minutos",
    genre: ["Acción", "Drama", "Ciencia ficción"],
    releaseDate: "3 de marzo de 2017",
  },
  {
    title: "Capitan America Guerra Civil",
    poster: "../images/12. Captain America Civil War.jpg",
    summary: "Los Vengadores se dividen por un conflicto político.",
    description: `Un enfrentamiento entre Steve Rogers y Tony Stark divide a los Vengadores en dos facciones, enfrentando amigos contra amigos mientras intentan lidiar con un nuevo tipo de amenaza.`,
    cast: [
      "Chris Evans - Steve Rogers / Capitán América",
      "Robert Downey Jr. - Tony Stark / Iron Man",
      "Scarlett Johansson - Natasha Romanoff / Black Widow",
      "Sebastian Stan - Bucky Barnes / Winter Soldier",
      "Anthony Mackie - Sam Wilson / Falcon",
    ],
    duration: "147 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "6 de mayo de 2016",
  },
  {
    title: "Aquaman",
    poster: "../images/13. Aquaman.jpg",
    summary: "Arthur Curry descubre su destino como gobernante de Atlantis.",
    description: `Metido entre dos mundos, el terrestre y el submarino, Arthur Curry debe aceptar su destino como Aquaman y liderar a Atlantis contra un medio hermano que amenaza con guerra.`,
    cast: [
      "Jason Momoa - Arthur Curry / Aquaman",
      "Amber Heard - Mera",
      "Willem Dafoe - Vulko",
      "Patrick Wilson - Orm",
      "Nicole Kidman - Atlanna",
    ],
    duration: "143 minutos",
    genre: ["Acción", "Aventura", "Fantasía"],
    releaseDate: "21 de diciembre de 2018",
  },
  {
    title: "The Amazing Spider-Man",
    poster: "../images/14. The Amazing Spider-Man.jpg",
    summary: "Peter Parker enfrenta a un enemigo reptiliano.",
    description: `Peter Parker descubre pistas sobre la desaparición de sus padres mientras enfrenta al Dr. Curt Connors, quien se ha transformado en el peligroso villano Lizard.`,
    cast: [
      "Andrew Garfield - Peter Parker / Spider-Man",
      "Emma Stone - Gwen Stacy",
      "Rhys Ifans - Dr. Curt Connors / Lizard",
      "Denis Leary - Capitán Stacy",
      "Martin Sheen - Tío Ben",
    ],
    duration: "136 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "3 de julio de 2012",
  },
  {
    title: "Doctor Strange",
    poster: "../images/15. Doctor Strange.jpg",
    summary:
      "Un neurocirujano descubre un mundo de magia y dimensiones alternativas.",
    description: `Después de un accidente que arruina sus manos, el brillante pero arrogante Dr. Stephen Strange busca curación y encuentra un mundo de magia y dimensiones alternativas.`,
    cast: [
      "Benedict Cumberbatch - Dr. Stephen Strange",
      "Chiwetel Ejiofor - Karl Mordo",
      "Rachel McAdams - Christine Palmer",
      "Tilda Swinton - Ancient One",
      "Mads Mikkelsen - Kaecilius",
    ],
    duration: "115 minutos",
    genre: ["Acción", "Aventura", "Fantasía"],
    releaseDate: "4 de noviembre de 2016",
  },
  {
    title: "Shazam",
    poster: "../images/16. Shazam.jpg",
    summary:
      "Un niño obtiene poderes mágicos para transformarse en un superhéroe adulto.",
    description: `Billy Batson, un adolescente, recibe la capacidad de transformarse en un superhéroe adulto pronunciando la palabra "Shazam". Debe aprender a usar sus poderes para enfrentarse al malvado Dr. Sivana.`,
    cast: [
      "Zachary Levi - Shazam",
      "Asher Angel - Billy Batson",
      "Mark Strong - Dr. Thaddeus Sivana",
      "Jack Dylan Grazer - Freddy Freeman",
      "Djimon Hounsou - El Mago",
    ],
    duration: "132 minutos",
    genre: ["Acción", "Comedia", "Fantasía"],
    releaseDate: "5 de abril de 2019",
  },
  {
    title: "Venom",
    poster: "../images/17. Venom.jpg",
    summary: "Un reportero se fusiona con un simbionte alienígena.",
    description: `Eddie Brock, un reportero, adquiere superpoderes cuando se convierte en el huésped de un simbionte alienígena. Mientras aprende a controlar sus nuevos poderes, enfrenta amenazas tanto humanas como extraterrestres.`,
    cast: [
      "Tom Hardy - Eddie Brock / Venom",
      "Michelle Williams - Anne Weying",
      "Riz Ahmed - Carlton Drake / Riot",
      "Reid Scott - Dan Lewis",
      "Jenny Slate - Dora Skirth",
    ],
    duration: "112 minutos",
    genre: ["Acción", "Ciencia ficción", "Terror"],
    releaseDate: "5 de octubre de 2018",
  },
  {
    title: "Ant-Man: El Hombre Hormiga",
    poster: "../images/18. Ant-Man.jpg",
    summary: "Un ladrón reformado se convierte en el diminuto héroe Ant-Man.",
    description: `Scott Lang, un ladrón reformado, es reclutado por el Dr. Hank Pym para proteger la tecnología de encogimiento y asumir el rol de Ant-Man, enfrentándose a una amenaza que busca explotar esta tecnología.`,
    cast: [
      "Paul Rudd - Scott Lang / Ant-Man",
      "Evangeline Lilly - Hope van Dyne",
      "Michael Douglas - Dr. Hank Pym",
      "Corey Stoll - Darren Cross / Yellowjacket",
      "Michael Peña - Luis",
    ],
    duration: "117 minutos",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    releaseDate: "17 de julio de 2015",
  },
  {
    title: "El Escuadrón Suicida",
    poster: "../images/19. The Suicide Squad.jpg",
    summary:
      "Un grupo de villanos realiza una misión suicida en una isla remota.",
    description: `Un grupo de supervillanos encarcelados recibe la oportunidad de reducir sus sentencias al completar una misión peligrosa en una isla remota llena de secretos mortales.`,
    cast: [
      "Margot Robbie - Harley Quinn",
      "Idris Elba - Bloodsport",
      "John Cena - Peacemaker",
      "Joel Kinnaman - Rick Flag",
      "Viola Davis - Amanda Waller",
    ],
    duration: "132 minutos",
    genre: ["Acción", "Comedia", "Aventura"],
    releaseDate: "6 de agosto de 2021",
  },
  {
    title: "Batman inicia",
    poster: "../images/20. Batman Begins.jpg",
    summary: "El origen de Batman y su lucha contra el crimen en Gotham.",
    description: `Bruce Wayne regresa a Gotham después de años de entrenamiento para combatir el crimen. Asume la identidad de Batman y enfrenta a la Liga de las Sombras y a villanos que amenazan la ciudad.`,
    cast: [
      "Christian Bale - Bruce Wayne / Batman",
      "Michael Caine - Alfred Pennyworth",
      "Liam Neeson - Ra's al Ghul",
      "Katie Holmes - Rachel Dawes",
      "Gary Oldman - James Gordon",
    ],
    duration: "140 minutos",
    genre: ["Acción", "Aventura", "Drama"],
    releaseDate: "15 de junio de 2005",
  },
];
